#!/bin/sh

# se neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"


# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	apt="sudo apt-get" \
	clip="clip.exe" \
        brave='"/c/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"' \
	subl='"/c/Program Files/Sublime Text 3/subl.exe"' \
	sz="source ~/.config/zsh/.zshrc" \



